version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3308:3306"               # Expose MySQL on host port 3308 (your existing local port)
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mr_store
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
